init:
  - git config --global core.autocrlf true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install tape

build: off

test_script:
  - ps: 'npm run-script test-node #PowerShell'
  - ps: 'npm run-script test-cli #PowerShell'
  - cmd: npm run-script test-node
  - cmd: npm run-script test-cli

cache:
  - node_modules
